stages:
  - linting
  - build
  - test

.docker-base:
  image: docker:20.10.11
  services:
    - docker:20.10.11-dind
  variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

.hadolint:
  extends:
    - .docker-base
  script:
    - docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile

.buildDockerImage:
  extends:
    - .docker-base
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/${APP_NAME} .
    - docker push $CI_REGISTRY_IMAGE/${APP_NAME}:${DOCKER_TAG}
  after_script:
    - docker logout $CI_REGISTRY

# Dockerfile Linting:
#   stage: linting
#   extends:
#     - .hadolint

Build container:
  stage: build
  extends:
    - .buildDockerImage
  variables:
    APP_NAME: iperf2
    DOCKER_TAG: latest

Test Container:
  stage: test
  extends:
    - .docker-base
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker run --rm -i $CI_REGISTRY_IMAGE/${APP_NAME}:${DOCKER_TAG} --help
  after_script:
    - docker logout $CI_REGISTRY
