variables:
  APP_NAME: iperf2
  DOCKER_TAG: latest

stages:
  - linting
  - build
  - test

include:
  - local: /pipelines/docker-template.yml

Dockerfile Linting:
  stage: linting
  needs: []
  extends:
    - .hadolint

Build container:
  stage: build
  needs: ["Dockerfile Linting"]
  extends:
    - .buildContainer

Test Container:
  stage: test
  needs: ["Build container"]
  extends:
    - .containerBase
  script:
    - "docker run --rm $CI_REGISTRY_IMAGE/${APP_NAME}:${DOCKER_TAG} -s -t3"