variables:
  APP_NAME: iperf2
  DOCKER_TAG: latest

stages:
  - linting
  - build
  - test

.containerBase:
  image: docker:20.10.11
  services:
    - docker:20.10.11-dind
  variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY

.hadolint:
  extends:
    - .containerBase
  script:
    - docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile

.buildContainer:
  extends:
    - .containerBase
  script:
    - docker build -t $CI_REGISTRY_IMAGE/${APP_NAME} .
    - docker push $CI_REGISTRY_IMAGE/${APP_NAME}:${DOCKER_TAG}

Dockerfile Linting:
  stage: linting
  needs: []
  extends:
    - .hadolint

Build container:
  stage: build
  needs: ["Dockerfile Linting"]
  extends:
    - .buildContainer

Test Container:
  stage: test
  needs: ["Build container"]
  extends:
    - .containerBase
  script:
    - echo $CI_REGISTRY_IMAGE/${APP_NAME}:${DOCKER_TAG}
    - docker run --rm -i $CI_REGISTRY_IMAGE/${APP_NAME}:${DOCKER_TAG} --help