stages:
  - build

.buildDockerImage:
  image: docker:19.03.1
  services:
  - docker:19.03.1-dind
  variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t ${APP_NAME} .
    - docker push ${APP_NAME}:${DOCKER_TAG}

build-image:
  stage: build
  extends:
    - .buildDockerImage
  variables:
    APP_NAME: iperf2
    DOCKER_TAG: latest